TerminalDX12: TerminalDX12::Pty::ConPtySession Class Reference
TerminalDX12::Pty::ConPtySession Class Reference
#include <ConPtySession.h>
Public Types
using OutputCallback = std::function<void(const char* data, size_t size)>
using ProcessExitCallback = std::function<void(int exitCode)>
Public Member Functions
ConPtySession ()
~ConPtySession ()
bool Start (const std::wstring &commandline, int cols, int rows)
void Stop ()
bool WriteInput (const char *data, size_t size)
bool WriteInput (const std::string &data)
bool Resize (int cols, int rows)
void SetOutputCallback (OutputCallback callback)
void SetProcessExitCallback (ProcessExitCallback callback)
bool IsRunning () const
Detailed Description
Definition at line 13 of file ConPtySession.h.
Member Typedef Documentation
OutputCallback
using TerminalDX12::Pty::ConPtySession::OutputCallback = std::function<void(const char* data, size_t size)>
Definition at line 19 of file ConPtySession.h.
ProcessExitCallback
using TerminalDX12::Pty::ConPtySession::ProcessExitCallback = std::function<void(int exitCode)>
Definition at line 22 of file ConPtySession.h.
Constructor & Destructor Documentation
ConPtySession()
TerminalDX12::Pty::ConPtySession::ConPtySession ()
Definition at line 8 of file ConPtySession.cpp.
~ConPtySession()
TerminalDX12::Pty::ConPtySession::~ConPtySession ()
Definition at line 22 of file ConPtySession.cpp.
References Stop().
Member Function Documentation
IsRunning()
bool TerminalDX12::Pty::ConPtySession::IsRunning () const inline
Definition at line 44 of file ConPtySession.h.
Resize()
bool TerminalDX12::Pty::ConPtySession::Resize (int cols, int rows)
Definition at line 227 of file ConPtySession.cpp.
SetOutputCallback()
void TerminalDX12::Pty::ConPtySession::SetOutputCallback (OutputCallback callback)
Definition at line 247 of file ConPtySession.cpp.
SetProcessExitCallback()
void TerminalDX12::Pty::ConPtySession::SetProcessExitCallback (ProcessExitCallback callback)
Definition at line 251 of file ConPtySession.cpp.
Start()
bool TerminalDX12::Pty::ConPtySession::Start (const std::wstring & commandline, int cols, int rows)
Definition at line 26 of file ConPtySession.cpp.
Stop()
void TerminalDX12::Pty::ConPtySession::Stop ()
Definition at line 158 of file ConPtySession.cpp.
Referenced by ~ConPtySession().
WriteInput() [1/2]
bool TerminalDX12::Pty::ConPtySession::WriteInput (const char * data, size_t size)
Definition at line 207 of file ConPtySession.cpp.
Referenced by WriteInput().
WriteInput() [2/2]
bool TerminalDX12::Pty::ConPtySession::WriteInput (const std::string & data)
Definition at line 223 of file ConPtySession.cpp.
References WriteInput().
The documentation for this class was generated from the following files:
include/pty/ConPtySession.h
src/pty/ConPtySession.cpp