TerminalDX12: TerminalDX12::Terminal::ScreenBuffer Class Reference
TerminalDX12::Terminal::ScreenBuffer Class Reference
#include <ScreenBuffer.h>
Public Member Functions
ScreenBuffer (int cols=80, int rows=24, int scrollbackLines=10000)
~ScreenBuffer ()
void Resize (int cols, int rows)
int GetCols () const
int GetRows () const
void SetCursorPos (int x, int y)
void GetCursorPos (int &x, int &y) const
int GetCursorX () const
int GetCursorY () const
void SetCursorVisible (bool visible)
bool IsCursorVisible () const
void WriteChar (char32_t ch)
void WriteChar (char32_t ch, const CellAttributes &attr)
void WriteString (const std::u32string &str)
void ScrollUp (int lines=1)
void ScrollDown (int lines=1)
void ScrollToBottom ()
int GetScrollOffset () const
void SetScrollOffset (int offset)
void SetScrollRegion (int top, int bottom)
void ResetScrollRegion ()
int GetScrollRegionTop () const
int GetScrollRegionBottom () const
void ScrollRegionUp (int lines=1)
void ScrollRegionDown (int lines=1)
void Clear ()
void ClearLine (int y)
void ClearLine (int y, int startX, int endX)
void ClearRect (int x, int y, int width, int height)
void SetCurrentAttributes (const CellAttributes &attr)
const CellAttributes & GetCurrentAttributes () const
const Cell & GetCell (int x, int y) const
Cell & GetCellMutable (int x, int y)
const Cell & GetCellWithScrollback (int x, int y) const
const std::vector< Cell > & GetBuffer () const
bool IsDirty () const
void ClearDirty ()
void MarkDirty ()
void UseAlternativeBuffer (bool use)
bool IsUsingAlternativeBuffer () const
void MarkPromptStart ()
void MarkInputStart ()
void MarkCommandStart ()
void MarkCommandEnd (int exitCode=-1)
SemanticZone GetCurrentZone () const
int GetPreviousPromptLine (int fromLine) const
int GetNextPromptLine (int fromLine) const
const std::vector< PromptMarker > & GetPromptMarkers () const
void SetTabStop (int column)
void ClearTabStop (int column)
void ClearAllTabStops ()
void ResetTabStops ()
uint16_t AddHyperlink (const std::string &url, const std::string &id="")
void ClearCurrentHyperlink ()
const Hyperlink * GetHyperlink (uint16_t id) const
uint16_t GetCurrentHyperlinkId () const
void SetPaletteColor (int index, uint8_t r, uint8_t g, uint8_t b)
const PaletteColor & GetPaletteColor (int index) const
bool IsPaletteColorModified (int index) const
void ResetPaletteColor (int index)
void ResetAllPaletteColors ()
Detailed Description
Definition at line 137 of file ScreenBuffer.h.
Constructor & Destructor Documentation
ScreenBuffer()
TerminalDX12::Terminal::ScreenBuffer::ScreenBuffer (int cols = 80, int rows = 24, int scrollbackLines = 10000)
Definition at line 7 of file ScreenBuffer.cpp.
References ResetTabStops().
~ScreenBuffer()
TerminalDX12::Terminal::ScreenBuffer::~ScreenBuffer ()
Definition at line 32 of file ScreenBuffer.cpp.
Member Function Documentation
AddHyperlink()
uint16_t TerminalDX12::Terminal::ScreenBuffer::AddHyperlink (const std::string & url, const std::string & id = "")
Definition at line 661 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::CellAttributes::FLAG2_HYPERLINK.
Clear()
void TerminalDX12::Terminal::ScreenBuffer::Clear ()
Definition at line 335 of file ScreenBuffer.cpp.
ClearAllTabStops()
void TerminalDX12::Terminal::ScreenBuffer::ClearAllTabStops ()
Definition at line 516 of file ScreenBuffer.cpp.
ClearCurrentHyperlink()
void TerminalDX12::Terminal::ScreenBuffer::ClearCurrentHyperlink ()
Definition at line 688 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::CellAttributes::hyperlinkId.
ClearDirty()
void TerminalDX12::Terminal::ScreenBuffer::ClearDirty () inline
Definition at line 197 of file ScreenBuffer.h.
ClearLine() [1/2]
void TerminalDX12::Terminal::ScreenBuffer::ClearLine (int y)
Definition at line 344 of file ScreenBuffer.cpp.
References ClearLine().
Referenced by ClearLine(), and ClearRect().
ClearLine() [2/2]
void TerminalDX12::Terminal::ScreenBuffer::ClearLine (int y, int startX, int endX)
Definition at line 350 of file ScreenBuffer.cpp.
ClearRect()
void TerminalDX12::Terminal::ScreenBuffer::ClearRect (int x, int y, int width, int height)
Definition at line 364 of file ScreenBuffer.cpp.
References ClearLine().
ClearTabStop()
void TerminalDX12::Terminal::ScreenBuffer::ClearTabStop (int column)
Definition at line 510 of file ScreenBuffer.cpp.
GetBuffer()
const std::vector< Cell > & TerminalDX12::Terminal::ScreenBuffer::GetBuffer () const inline
Definition at line 193 of file ScreenBuffer.h.
GetCell()
const Cell & TerminalDX12::Terminal::ScreenBuffer::GetCell (int x, int y) const
Definition at line 370 of file ScreenBuffer.cpp.
GetCellMutable()
Cell & TerminalDX12::Terminal::ScreenBuffer::GetCellMutable (int x, int y)
Definition at line 380 of file ScreenBuffer.cpp.
GetCellWithScrollback()
const Cell & TerminalDX12::Terminal::ScreenBuffer::GetCellWithScrollback (int x, int y) const
Definition at line 391 of file ScreenBuffer.cpp.
GetCols()
int TerminalDX12::Terminal::ScreenBuffer::GetCols () const inline
Definition at line 144 of file ScreenBuffer.h.
GetCurrentAttributes()
const CellAttributes & TerminalDX12::Terminal::ScreenBuffer::GetCurrentAttributes () const inline
Definition at line 183 of file ScreenBuffer.h.
GetCurrentHyperlinkId()
uint16_t TerminalDX12::Terminal::ScreenBuffer::GetCurrentHyperlinkId () const inline
Definition at line 226 of file ScreenBuffer.h.
GetCurrentZone()
SemanticZone TerminalDX12::Terminal::ScreenBuffer::GetCurrentZone () const inline
Definition at line 209 of file ScreenBuffer.h.
GetCursorPos()
void TerminalDX12::Terminal::ScreenBuffer::GetCursorPos (int & x, int & y) const inline
Definition at line 149 of file ScreenBuffer.h.
GetCursorX()
int TerminalDX12::Terminal::ScreenBuffer::GetCursorX () const inline
Definition at line 150 of file ScreenBuffer.h.
GetCursorY()
int TerminalDX12::Terminal::ScreenBuffer::GetCursorY () const inline
Definition at line 151 of file ScreenBuffer.h.
GetHyperlink()
const Hyperlink * TerminalDX12::Terminal::ScreenBuffer::GetHyperlink (uint16_t id) const
Definition at line 694 of file ScreenBuffer.cpp.
GetNextPromptLine()
int TerminalDX12::Terminal::ScreenBuffer::GetNextPromptLine (int fromLine) const
Definition at line 650 of file ScreenBuffer.cpp.
GetPaletteColor()
const PaletteColor & TerminalDX12::Terminal::ScreenBuffer::GetPaletteColor (int index) const
Definition at line 712 of file ScreenBuffer.cpp.
GetPreviousPromptLine()
int TerminalDX12::Terminal::ScreenBuffer::GetPreviousPromptLine (int fromLine) const
Definition at line 637 of file ScreenBuffer.cpp.
GetPromptMarkers()
const std::vector< PromptMarker > & TerminalDX12::Terminal::ScreenBuffer::GetPromptMarkers () const inline
Definition at line 214 of file ScreenBuffer.h.
GetRows()
int TerminalDX12::Terminal::ScreenBuffer::GetRows () const inline
Definition at line 145 of file ScreenBuffer.h.
GetScrollOffset()
int TerminalDX12::Terminal::ScreenBuffer::GetScrollOffset () const inline
Definition at line 164 of file ScreenBuffer.h.
GetScrollRegionBottom()
int TerminalDX12::Terminal::ScreenBuffer::GetScrollRegionBottom () const
Definition at line 547 of file ScreenBuffer.cpp.
Referenced by ScrollRegionDown(), ScrollRegionUp(), ScrollUp(), and WriteChar().
GetScrollRegionTop()
int TerminalDX12::Terminal::ScreenBuffer::GetScrollRegionTop () const inline
Definition at line 170 of file ScreenBuffer.h.
IsCursorVisible()
bool TerminalDX12::Terminal::ScreenBuffer::IsCursorVisible () const inline
Definition at line 153 of file ScreenBuffer.h.
IsDirty()
bool TerminalDX12::Terminal::ScreenBuffer::IsDirty () const inline
Definition at line 196 of file ScreenBuffer.h.
IsPaletteColorModified()
bool TerminalDX12::Terminal::ScreenBuffer::IsPaletteColorModified (int index) const
Definition at line 718 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::PaletteColor::modified.
IsUsingAlternativeBuffer()
bool TerminalDX12::Terminal::ScreenBuffer::IsUsingAlternativeBuffer () const inline
Definition at line 202 of file ScreenBuffer.h.
MarkCommandEnd()
void TerminalDX12::Terminal::ScreenBuffer::MarkCommandEnd (int exitCode = -1)
Definition at line 626 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::None.
MarkCommandStart()
void TerminalDX12::Terminal::ScreenBuffer::MarkCommandStart ()
Definition at line 621 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::Output.
MarkDirty()
void TerminalDX12::Terminal::ScreenBuffer::MarkDirty () inline
Definition at line 198 of file ScreenBuffer.h.
MarkInputStart()
void TerminalDX12::Terminal::ScreenBuffer::MarkInputStart ()
Definition at line 616 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::Input.
MarkPromptStart()
void TerminalDX12::Terminal::ScreenBuffer::MarkPromptStart ()
Definition at line 601 of file ScreenBuffer.cpp.
References TerminalDX12::Terminal::PromptMarker::absoluteLine, TerminalDX12::Terminal::PromptMarker::exitCode, and TerminalDX12::Terminal::Prompt.
ResetAllPaletteColors()
void TerminalDX12::Terminal::ScreenBuffer::ResetAllPaletteColors ()
Definition at line 729 of file ScreenBuffer.cpp.
ResetPaletteColor()
void TerminalDX12::Terminal::ScreenBuffer::ResetPaletteColor (int index)
Definition at line 723 of file ScreenBuffer.cpp.
ResetScrollRegion()
void TerminalDX12::Terminal::ScreenBuffer::ResetScrollRegion ()
Definition at line 541 of file ScreenBuffer.cpp.
Referenced by SetScrollRegion().
ResetTabStops()
void TerminalDX12::Terminal::ScreenBuffer::ResetTabStops ()
Definition at line 520 of file ScreenBuffer.cpp.
Referenced by ScreenBuffer().
Resize()
void TerminalDX12::Terminal::ScreenBuffer::Resize (int cols, int rows)
Definition at line 35 of file ScreenBuffer.cpp.
ScrollDown()
void TerminalDX12::Terminal::ScreenBuffer::ScrollDown (int lines = 1)
Definition at line 307 of file ScreenBuffer.cpp.
ScrollRegionDown()
void TerminalDX12::Terminal::ScreenBuffer::ScrollRegionDown (int lines = 1)
Definition at line 576 of file ScreenBuffer.cpp.
References GetScrollRegionBottom().
ScrollRegionUp()
void TerminalDX12::Terminal::ScreenBuffer::ScrollRegionUp (int lines = 1)
Definition at line 551 of file ScreenBuffer.cpp.
References GetScrollRegionBottom().
Referenced by WriteChar().
ScrollToBottom()
void TerminalDX12::Terminal::ScreenBuffer::ScrollToBottom ()
Definition at line 325 of file ScreenBuffer.cpp.
ScrollUp()
void TerminalDX12::Terminal::ScreenBuffer::ScrollUp (int lines = 1)
Definition at line 250 of file ScreenBuffer.cpp.
References GetScrollRegionBottom().
Referenced by WriteChar().
SetCurrentAttributes()
void TerminalDX12::Terminal::ScreenBuffer::SetCurrentAttributes (const CellAttributes & attr) inline
Definition at line 182 of file ScreenBuffer.h.
SetCursorPos()
void TerminalDX12::Terminal::ScreenBuffer::SetCursorPos (int x, int y)
Definition at line 172 of file ScreenBuffer.cpp.
SetCursorVisible()
void TerminalDX12::Terminal::ScreenBuffer::SetCursorVisible (bool visible) inline
Definition at line 152 of file ScreenBuffer.h.
SetPaletteColor()
void TerminalDX12::Terminal::ScreenBuffer::SetPaletteColor (int index, uint8_t r, uint8_t g, uint8_t b)
Definition at line 703 of file ScreenBuffer.cpp.
SetScrollOffset()
void TerminalDX12::Terminal::ScreenBuffer::SetScrollOffset (int offset)
Definition at line 330 of file ScreenBuffer.cpp.
SetScrollRegion()
void TerminalDX12::Terminal::ScreenBuffer::SetScrollRegion (int top, int bottom)
Definition at line 529 of file ScreenBuffer.cpp.
References ResetScrollRegion().
SetTabStop()
void TerminalDX12::Terminal::ScreenBuffer::SetTabStop (int column)
Definition at line 501 of file ScreenBuffer.cpp.
UseAlternativeBuffer()
void TerminalDX12::Terminal::ScreenBuffer::UseAlternativeBuffer (bool use)
Definition at line 420 of file ScreenBuffer.cpp.
WriteChar() [1/2]
void TerminalDX12::Terminal::ScreenBuffer::WriteChar (char32_t ch)
Definition at line 183 of file ScreenBuffer.cpp.
References WriteChar().
Referenced by WriteChar(), and WriteString().
WriteChar() [2/2]
void TerminalDX12::Terminal::ScreenBuffer::WriteChar (char32_t ch, const CellAttributes & attr)
Definition at line 187 of file ScreenBuffer.cpp.
References GetScrollRegionBottom(), ScrollRegionUp(), and ScrollUp().
WriteString()
void TerminalDX12::Terminal::ScreenBuffer::WriteString (const std::u32string & str)
Definition at line 244 of file ScreenBuffer.cpp.
References WriteChar().
The documentation for this class was generated from the following files:
include/terminal/ScreenBuffer.h
src/terminal/ScreenBuffer.cpp