TerminalDX12: TerminalDX12::Core::Application Class Reference
TerminalDX12::Core::Application Class Reference
Main application class managing the terminal emulator lifecycle.
#include <Application.h>
Public Member Functions
Application ()
~Application ()
bool Initialize (const std::wstring &shell=L"powershell.exe")
Initialize the terminal application.
int Run ()
Run the main application loop.
void Shutdown ()
Clean up resources and prepare for exit.
Window * GetWindow ()
Static Public Member Functions
static Application & Get ()
Detailed Description
Main application class managing the terminal emulator lifecycle.
Application is the central coordinator for TerminalDX12. It manages:
Window creation and event handling
DirectX 12 rendering pipeline
Terminal emulation via ConPTY
Text selection and clipboard operations
Mouse and keyboard input processing
Tab management for multiple terminal sessions
Note
This class follows a singleton pattern accessible via Get()
Definition at line 62 of file Application.h.
Constructor & Destructor Documentation
Application()
TerminalDX12::Core::Application::Application ()
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 45 of file Application.cpp.
Referenced by Get().
~Application()
TerminalDX12::Core::Application::~Application ()
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 61 of file Application.cpp.
References Shutdown().
Member Function Documentation
Get()
Application & TerminalDX12::Core::Application::Get () inline static
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 85 of file Application.h.
References Application().
GetWindow()
Window * TerminalDX12::Core::Application::GetWindow () inline
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 86 of file Application.h.
Initialize()
bool TerminalDX12::Core::Application::Initialize (const std::wstring & shell = L"powershell.exe") nodiscard
Initialize the terminal application.
Parameters
shell Path to the shell executable (default: powershell.exe)
Returns
true if initialization succeeded, false on error
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 66 of file Application.cpp.
References TerminalDX12::UI::Tab::GetTerminal(), TerminalDX12::Core::WindowDesc::height, TerminalDX12::UI::Tab::IsRunning(), TerminalDX12::Core::WindowDesc::resizable, TerminalDX12::UI::Tab::SetClipboardReadCallback(), TerminalDX12::UI::Tab::SetClipboardWriteCallback(), TerminalDX12::Core::WindowDesc::title, and TerminalDX12::Core::WindowDesc::width.
Referenced by wWinMain().
Run()
int TerminalDX12::Core::Application::Run ()
Run the main application loop.
Returns
Exit code (0 for success)
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 264 of file Application.cpp.
Referenced by wWinMain().
Shutdown()
void TerminalDX12::Core::Application::Shutdown ()
Clean up resources and prepare for exit.
Examples
C:/Users/maxla/TerminalDX12/include/core/Application.h.
Definition at line 216 of file Application.cpp.
Referenced by wWinMain(), and ~Application().
The documentation for this class was generated from the following files:
include/core/Application.h
src/core/Application.cpp