TerminalDX12: TerminalDX12::Rendering::TextRenderer Class Reference
TerminalDX12::Rendering::TextRenderer Class Reference
#include <TextRenderer.h>
Public Member Functions
TextRenderer ()
~TextRenderer ()
bool Initialize (ID3D12Device *device, GlyphAtlas *atlas, int screenWidth, int screenHeight)
void Shutdown ()
void RenderText (const std::string &text, float x, float y, const XMFLOAT4 &color)
void RenderText (const std::u32string &text, float x, float y, const XMFLOAT4 &color)
void RenderCharAtCell (const std::string &ch, float x, float y, const XMFLOAT4 &color)
void RenderRect (float x, float y, float width, float height, float r, float g, float b, float a=1.0f)
void Clear ()
void Render (ID3D12GraphicsCommandList *commandList)
void SetScreenSize (int width, int height)
void SetRootSignature (ID3D12RootSignature *rootSignature)
void SetPipelineState (ID3D12PipelineState *pso)
Detailed Description
Definition at line 24 of file TextRenderer.h.
Constructor & Destructor Documentation
TextRenderer()
TerminalDX12::Rendering::TextRenderer::TextRenderer ()
Definition at line 41 of file TextRenderer.cpp.
~TextRenderer()
TerminalDX12::Rendering::TextRenderer::~TextRenderer ()
Definition at line 51 of file TextRenderer.cpp.
References Shutdown().
Member Function Documentation
Clear()
void TerminalDX12::Rendering::TextRenderer::Clear ()
Definition at line 131 of file TextRenderer.cpp.
Initialize()
bool TerminalDX12::Rendering::TextRenderer::Initialize (ID3D12Device * device, GlyphAtlas * atlas, int screenWidth, int screenHeight) nodiscard
Definition at line 55 of file TextRenderer.cpp.
Render()
void TerminalDX12::Rendering::TextRenderer::Render (ID3D12GraphicsCommandList * commandList)
Definition at line 316 of file TextRenderer.cpp.
RenderCharAtCell()
void TerminalDX12::Rendering::TextRenderer::RenderCharAtCell (const std::string & ch, float x, float y, const XMFLOAT4 & color)
Definition at line 199 of file TextRenderer.cpp.
References TerminalDX12::Rendering::GlyphInfo::bearingX, TerminalDX12::Rendering::GlyphInfo::bearingY, TerminalDX12::Rendering::GlyphInstance::color, TerminalDX12::Rendering::GlyphInfo::height, TerminalDX12::Rendering::GlyphInstance::position, TerminalDX12::Rendering::GlyphInstance::size, TerminalDX12::Rendering::GlyphInfo::u0, TerminalDX12::Rendering::GlyphInfo::u1, TerminalDX12::Rendering::GlyphInstance::uvMax, TerminalDX12::Rendering::GlyphInstance::uvMin, TerminalDX12::Rendering::GlyphInfo::v0, TerminalDX12::Rendering::GlyphInfo::v1, and TerminalDX12::Rendering::GlyphInfo::width.
RenderRect()
void TerminalDX12::Rendering::TextRenderer::RenderRect (float x, float y, float width, float height, float r, float g, float b, float a = 1.0f)
Definition at line 246 of file TextRenderer.cpp.
References TerminalDX12::Rendering::GlyphInstance::color, TerminalDX12::Rendering::GlyphInstance::position, TerminalDX12::Rendering::GlyphInstance::size, TerminalDX12::Rendering::GlyphInfo::u0, TerminalDX12::Rendering::GlyphInfo::u1, TerminalDX12::Rendering::GlyphInstance::uvMax, TerminalDX12::Rendering::GlyphInstance::uvMin, TerminalDX12::Rendering::GlyphInfo::v0, and TerminalDX12::Rendering::GlyphInfo::v1.
RenderText() [1/2]
void TerminalDX12::Rendering::TextRenderer::RenderText (const std::string & text, float x, float y, const XMFLOAT4 & color)
Definition at line 135 of file TextRenderer.cpp.
References RenderText().
Referenced by RenderText().
RenderText() [2/2]
void TerminalDX12::Rendering::TextRenderer::RenderText (const std::u32string & text, float x, float y, const XMFLOAT4 & color)
Definition at line 141 of file TextRenderer.cpp.
References TerminalDX12::Rendering::GlyphInfo::advance, TerminalDX12::Rendering::GlyphInfo::bearingX, TerminalDX12::Rendering::GlyphInfo::bearingY, TerminalDX12::Rendering::GlyphInstance::color, TerminalDX12::Rendering::GlyphInfo::height, TerminalDX12::Rendering::GlyphInstance::position, TerminalDX12::Rendering::GlyphInstance::size, TerminalDX12::Rendering::GlyphInfo::u0, TerminalDX12::Rendering::GlyphInfo::u1, TerminalDX12::Rendering::GlyphInstance::uvMax, TerminalDX12::Rendering::GlyphInstance::uvMin, TerminalDX12::Rendering::GlyphInfo::v0, TerminalDX12::Rendering::GlyphInfo::v1, and TerminalDX12::Rendering::GlyphInfo::width.
SetPipelineState()
void TerminalDX12::Rendering::TextRenderer::SetPipelineState (ID3D12PipelineState * pso) inline
Definition at line 53 of file TextRenderer.h.
SetRootSignature()
void TerminalDX12::Rendering::TextRenderer::SetRootSignature (ID3D12RootSignature * rootSignature) inline
Definition at line 52 of file TextRenderer.h.
SetScreenSize()
void TerminalDX12::Rendering::TextRenderer::SetScreenSize (int width, int height)
Definition at line 292 of file TextRenderer.cpp.
Shutdown()
void TerminalDX12::Rendering::TextRenderer::Shutdown ()
Definition at line 70 of file TextRenderer.cpp.
Referenced by ~TextRenderer().
The documentation for this class was generated from the following files:
include/rendering/TextRenderer.h
src/rendering/TextRenderer.cpp