TerminalDX12: TerminalDX12::UI::Tab Class Reference
TerminalDX12::UI::Tab Class Reference
#include <Tab.h>
Public Member Functions
Tab (int id, int cols, int rows, int scrollbackLines=10000)
~Tab ()
bool Start (const std::wstring &shell)
void Stop ()
bool IsRunning () const
int GetId () const
const std::wstring & GetTitle () const
void SetTitle (const std::wstring &title)
bool HasActivity () const
void SetActivity (bool activity)
void ClearActivity ()
Terminal::ScreenBuffer * GetScreenBuffer ()
Terminal::VTStateMachine * GetVTParser ()
Pty::ConPtySession * GetTerminal ()
void WriteInput (const char *data, size_t size)
void SetOutputCallback (std::function< void(const char *, size_t)> callback)
void SetProcessExitCallback (std::function< void(int exitCode)> callback)
void SetClipboardReadCallback (std::function< std::string()> callback)
void SetClipboardWriteCallback (std::function< void(const std::string &)> callback)
void Resize (int cols, int rows)
void ResizeScreenBuffer (int cols, int rows)
void ResizeConPTY (int cols, int rows)
Detailed Description
Definition at line 18 of file Tab.h.
Constructor & Destructor Documentation
Tab()
TerminalDX12::UI::Tab::Tab (int id, int cols, int rows, int scrollbackLines = 10000)
Definition at line 9 of file Tab.cpp.
~Tab()
TerminalDX12::UI::Tab::~Tab ()
Definition at line 27 of file Tab.cpp.
References Stop().
Member Function Documentation
ClearActivity()
void TerminalDX12::UI::Tab::ClearActivity () inline
Definition at line 40 of file Tab.h.
GetId()
int TerminalDX12::UI::Tab::GetId () const inline
Definition at line 31 of file Tab.h.
GetScreenBuffer()
Terminal::ScreenBuffer * TerminalDX12::UI::Tab::GetScreenBuffer () inline
Definition at line 43 of file Tab.h.
GetTerminal()
Pty::ConPtySession * TerminalDX12::UI::Tab::GetTerminal () inline
Definition at line 45 of file Tab.h.
Referenced by TerminalDX12::Core::Application::Initialize().
GetTitle()
const std::wstring & TerminalDX12::UI::Tab::GetTitle () const inline
Definition at line 34 of file Tab.h.
GetVTParser()
Terminal::VTStateMachine * TerminalDX12::UI::Tab::GetVTParser () inline
Definition at line 44 of file Tab.h.
HasActivity()
bool TerminalDX12::UI::Tab::HasActivity () const inline
Definition at line 38 of file Tab.h.
IsRunning()
bool TerminalDX12::UI::Tab::IsRunning () const
Definition at line 90 of file Tab.cpp.
Referenced by TerminalDX12::Core::Application::Initialize().
Resize()
void TerminalDX12::UI::Tab::Resize (int cols, int rows)
Definition at line 120 of file Tab.cpp.
ResizeConPTY()
void TerminalDX12::UI::Tab::ResizeConPTY (int cols, int rows)
Definition at line 142 of file Tab.cpp.
ResizeScreenBuffer()
void TerminalDX12::UI::Tab::ResizeScreenBuffer (int cols, int rows)
Definition at line 133 of file Tab.cpp.
SetActivity()
void TerminalDX12::UI::Tab::SetActivity (bool activity) inline
Definition at line 39 of file Tab.h.
SetClipboardReadCallback()
void TerminalDX12::UI::Tab::SetClipboardReadCallback (std::function< std::string()> callback)
Definition at line 108 of file Tab.cpp.
Referenced by TerminalDX12::Core::Application::Initialize().
SetClipboardWriteCallback()
void TerminalDX12::UI::Tab::SetClipboardWriteCallback (std::function< void(const std::string &)> callback)
Definition at line 114 of file Tab.cpp.
Referenced by TerminalDX12::Core::Application::Initialize().
SetOutputCallback()
void TerminalDX12::UI::Tab::SetOutputCallback (std::function< void(const char *, size_t)> callback)
Definition at line 100 of file Tab.cpp.
SetProcessExitCallback()
void TerminalDX12::UI::Tab::SetProcessExitCallback (std::function< void(int exitCode)> callback)
Definition at line 104 of file Tab.cpp.
SetTitle()
void TerminalDX12::UI::Tab::SetTitle (const std::wstring & title) inline
Definition at line 35 of file Tab.h.
Start()
bool TerminalDX12::UI::Tab::Start (const std::wstring & shell)
Definition at line 32 of file Tab.cpp.
Stop()
void TerminalDX12::UI::Tab::Stop ()
Definition at line 84 of file Tab.cpp.
Referenced by ~Tab().
WriteInput()
void TerminalDX12::UI::Tab::WriteInput (const char * data, size_t size)
Definition at line 94 of file Tab.cpp.
The documentation for this class was generated from the following files:
include/ui/Tab.h
src/ui/Tab.cpp