TerminalDX12: TerminalDX12::Rendering::GlyphAtlas Class Reference
TerminalDX12::Rendering::GlyphAtlas Class Reference
#include <GlyphAtlas.h>
Public Member Functions
GlyphAtlas ()
~GlyphAtlas ()
bool Initialize (ID3D12Device *device, ID3D12GraphicsCommandList *commandList, const std::string &fontPath, int fontSize)
void Shutdown ()
const GlyphInfo * GetGlyph (char32_t codepoint, bool bold=false, bool italic=false)
std::vector< ShapedGlyph > ShapeText (const std::u32string &text, bool bold=false, bool italic=false)
bool LigaturesEnabled () const
void SetLigaturesEnabled (bool enabled)
D3D12_GPU_DESCRIPTOR_HANDLE GetAtlasSRV () const
int GetAtlasWidth () const
int GetAtlasHeight () const
int GetFontSize () const
int GetLineHeight () const
void UploadAtlasIfDirty ()
void PreloadASCIIGlyphs ()
const GlyphInfo * GetSolidGlyph () const
ID3D12DescriptorHeap * GetSRVHeap () const
Detailed Description
Definition at line 68 of file GlyphAtlas.h.
Constructor & Destructor Documentation
GlyphAtlas()
TerminalDX12::Rendering::GlyphAtlas::GlyphAtlas ()
Definition at line 22 of file GlyphAtlas.cpp.
~GlyphAtlas()
TerminalDX12::Rendering::GlyphAtlas::~GlyphAtlas ()
Definition at line 38 of file GlyphAtlas.cpp.
References Shutdown().
Member Function Documentation
GetAtlasHeight()
int TerminalDX12::Rendering::GlyphAtlas::GetAtlasHeight () const inline
Definition at line 93 of file GlyphAtlas.h.
GetAtlasSRV()
D3D12_GPU_DESCRIPTOR_HANDLE TerminalDX12::Rendering::GlyphAtlas::GetAtlasSRV () const inline
Definition at line 89 of file GlyphAtlas.h.
GetAtlasWidth()
int TerminalDX12::Rendering::GlyphAtlas::GetAtlasWidth () const inline
Definition at line 92 of file GlyphAtlas.h.
GetFontSize()
int TerminalDX12::Rendering::GlyphAtlas::GetFontSize () const inline
Definition at line 96 of file GlyphAtlas.h.
GetGlyph()
const GlyphInfo * TerminalDX12::Rendering::GlyphAtlas::GetGlyph (char32_t codepoint, bool bold = false, bool italic = false)
Definition at line 227 of file GlyphAtlas.cpp.
Referenced by PreloadASCIIGlyphs(), and ShapeText().
GetLineHeight()
int TerminalDX12::Rendering::GlyphAtlas::GetLineHeight () const inline
Definition at line 97 of file GlyphAtlas.h.
GetSolidGlyph()
const GlyphInfo * TerminalDX12::Rendering::GlyphAtlas::GetSolidGlyph () const inline
Definition at line 106 of file GlyphAtlas.h.
GetSRVHeap()
ID3D12DescriptorHeap * TerminalDX12::Rendering::GlyphAtlas::GetSRVHeap () const inline
Definition at line 109 of file GlyphAtlas.h.
Initialize()
bool TerminalDX12::Rendering::GlyphAtlas::Initialize (ID3D12Device * device, ID3D12GraphicsCommandList * commandList, const std::string & fontPath, int fontSize) nodiscard
Definition at line 42 of file GlyphAtlas.cpp.
References PreloadASCIIGlyphs().
LigaturesEnabled()
bool TerminalDX12::Rendering::GlyphAtlas::LigaturesEnabled () const inline
Definition at line 85 of file GlyphAtlas.h.
PreloadASCIIGlyphs()
void TerminalDX12::Rendering::GlyphAtlas::PreloadASCIIGlyphs ()
Definition at line 403 of file GlyphAtlas.cpp.
References GetGlyph().
Referenced by Initialize().
SetLigaturesEnabled()
void TerminalDX12::Rendering::GlyphAtlas::SetLigaturesEnabled (bool enabled) inline
Definition at line 86 of file GlyphAtlas.h.
ShapeText()
std::vector< ShapedGlyph > TerminalDX12::Rendering::GlyphAtlas::ShapeText (const std::u32string & text, bool bold = false, bool italic = false)
Definition at line 489 of file GlyphAtlas.cpp.
References TerminalDX12::Rendering::GlyphInfo::advance, TerminalDX12::Rendering::ShapedGlyph::clusterIndex, GetGlyph(), TerminalDX12::Rendering::ShapedGlyph::glyph, TerminalDX12::Rendering::ShapedGlyph::xAdvance, TerminalDX12::Rendering::ShapedGlyph::xOffset, and TerminalDX12::Rendering::ShapedGlyph::yOffset.
Shutdown()
void TerminalDX12::Rendering::GlyphAtlas::Shutdown ()
Definition at line 87 of file GlyphAtlas.cpp.
Referenced by ~GlyphAtlas().
UploadAtlasIfDirty()
void TerminalDX12::Rendering::GlyphAtlas::UploadAtlasIfDirty ()
Definition at line 322 of file GlyphAtlas.cpp.
The documentation for this class was generated from the following files:
include/rendering/GlyphAtlas.h
src/rendering/GlyphAtlas.cpp