TerminalDX12: TerminalDX12::Core::Window Class Reference
TerminalDX12::Core::Window Class Reference
Win32 window wrapper with DPI awareness and event callbacks.
#include <Window.h>
Public Member Functions
Window ()
~Window ()
bool Create (const WindowDesc &desc)
Create the window with specified parameters.
void Show ()
Show the window.
void Hide ()
Hide the window.
void Close ()
Close and destroy the window.
HWND GetHandle () const
int GetWidth () const
int GetHeight () const
float GetDPIScale () const
bool IsResizing () const
void SetTitle (const std::wstring &title)
void SetOpacity (float opacity)
Public Attributes
std::function< void(UINT key, bool isDown)> OnKeyEvent
std::function< void(wchar_t ch)> OnCharEvent
std::function< void(int width, int height)> OnResize
std::function< void()> OnPaint
std::function< void()> OnClose
std::function< void(int x, int y, int button, bool down)> OnMouseButton
std::function< void(int x, int y)> OnMouseMove
std::function< void(int delta)> OnMouseWheel
Detailed Description
Win32 window wrapper with DPI awareness and event callbacks.
Window provides a clean C++ interface for Win32 window management including:
Per-monitor DPI awareness V2
Event callbacks for keyboard, mouse, and window events
Resize state tracking for smooth terminal resize handling
Window opacity control for transparency effects
Definition at line 53 of file Window.h.
Constructor & Destructor Documentation
Window()
TerminalDX12::Core::Window::Window ()
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 7 of file Window.cpp.
~Window()
TerminalDX12::Core::Window::~Window ()
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 16 of file Window.cpp.
Member Function Documentation
Close()
void TerminalDX12::Core::Window::Close ()
Close and destroy the window.
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 91 of file Window.cpp.
Create()
bool TerminalDX12::Core::Window::Create (const WindowDesc & desc)
Create the window with specified parameters.
Parameters
desc Window configuration
Returns
true if window was created successfully
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 23 of file Window.cpp.
References TerminalDX12::Core::WindowDesc::height, TerminalDX12::Core::WindowDesc::resizable, TerminalDX12::Core::WindowDesc::title, and TerminalDX12::Core::WindowDesc::width.
GetDPIScale()
float TerminalDX12::Core::Window::GetDPIScale () const inline
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 78 of file Window.h.
GetHandle()
HWND TerminalDX12::Core::Window::GetHandle () const inline
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 75 of file Window.h.
Referenced by TerminalDX12::Rendering::DX12Renderer::Initialize().
GetHeight()
int TerminalDX12::Core::Window::GetHeight () const inline
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 77 of file Window.h.
Referenced by TerminalDX12::Rendering::DX12Renderer::Initialize().
GetWidth()
int TerminalDX12::Core::Window::GetWidth () const inline
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 76 of file Window.h.
Referenced by TerminalDX12::Rendering::DX12Renderer::Initialize().
Hide()
void TerminalDX12::Core::Window::Hide ()
Hide the window.
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 87 of file Window.cpp.
IsResizing()
bool TerminalDX12::Core::Window::IsResizing () const inline
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 79 of file Window.h.
SetOpacity()
void TerminalDX12::Core::Window::SetOpacity (float opacity)
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 99 of file Window.cpp.
SetTitle()
void TerminalDX12::Core::Window::SetTitle (const std::wstring & title)
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 95 of file Window.cpp.
Show()
void TerminalDX12::Core::Window::Show ()
Show the window.
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 82 of file Window.cpp.
Member Data Documentation
OnCharEvent
std::function<void(wchar_t ch)> TerminalDX12::Core::Window::OnCharEvent
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 87 of file Window.h.
OnClose
std::function<void()> TerminalDX12::Core::Window::OnClose
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 90 of file Window.h.
OnKeyEvent
std::function<void(UINT key, bool isDown)> TerminalDX12::Core::Window::OnKeyEvent
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 86 of file Window.h.
OnMouseButton
std::function<void(int x, int y, int button, bool down)> TerminalDX12::Core::Window::OnMouseButton
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 91 of file Window.h.
OnMouseMove
std::function<void(int x, int y)> TerminalDX12::Core::Window::OnMouseMove
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 92 of file Window.h.
OnMouseWheel
std::function<void(int delta)> TerminalDX12::Core::Window::OnMouseWheel
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 93 of file Window.h.
OnPaint
std::function<void()> TerminalDX12::Core::Window::OnPaint
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 89 of file Window.h.
OnResize
std::function<void(int width, int height)> TerminalDX12::Core::Window::OnResize
Examples
C:/Users/maxla/TerminalDX12/include/core/Window.h.
Definition at line 88 of file Window.h.
The documentation for this class was generated from the following files:
include/core/Window.h
src/core/Window.cpp