TerminalDX12: TerminalDX12::Core::Config Class Reference
TerminalDX12::Core::Config Class Reference
#include <Config.h>
Public Member Functions
Config ()
~Config ()=default
bool Load (const std::wstring &path)
bool LoadDefault ()
bool Save (const std::wstring &path) const
bool CreateDefaultIfMissing ()
const FontConfig & GetFont () const
const ColorConfig & GetColors () const
const KeybindingConfig & GetKeybindings () const
const TerminalConfig & GetTerminal () const
FontConfig & GetFontMut ()
ColorConfig & GetColorsMut ()
KeybindingConfig & GetKeybindingsMut ()
TerminalConfig & GetTerminalMut ()
bool IsLoaded () const
const std::vector< std::string > & GetWarnings () const
Static Public Member Functions
static std::wstring GetDefaultConfigPath ()
Detailed Description
Definition at line 106 of file Config.h.
Constructor & Destructor Documentation
Config()
TerminalDX12::Core::Config::Config ()
Definition at line 127 of file Config.cpp.
~Config()
TerminalDX12::Core::Config::~Config () default
Member Function Documentation
CreateDefaultIfMissing()
bool TerminalDX12::Core::Config::CreateDefaultIfMissing ()
Definition at line 448 of file Config.cpp.
References GetDefaultConfigPath(), and Save().
GetColors()
const ColorConfig & TerminalDX12::Core::Config::GetColors () const inline
Definition at line 128 of file Config.h.
GetColorsMut()
ColorConfig & TerminalDX12::Core::Config::GetColorsMut () inline
Definition at line 134 of file Config.h.
GetDefaultConfigPath()
std::wstring TerminalDX12::Core::Config::GetDefaultConfigPath () static
Definition at line 139 of file Config.cpp.
Referenced by CreateDefaultIfMissing(), and LoadDefault().
GetFont()
const FontConfig & TerminalDX12::Core::Config::GetFont () const inline
Definition at line 127 of file Config.h.
GetFontMut()
FontConfig & TerminalDX12::Core::Config::GetFontMut () inline
Definition at line 133 of file Config.h.
GetKeybindings()
const KeybindingConfig & TerminalDX12::Core::Config::GetKeybindings () const inline
Definition at line 129 of file Config.h.
GetKeybindingsMut()
KeybindingConfig & TerminalDX12::Core::Config::GetKeybindingsMut () inline
Definition at line 135 of file Config.h.
GetTerminal()
const TerminalConfig & TerminalDX12::Core::Config::GetTerminal () const inline
Definition at line 130 of file Config.h.
GetTerminalMut()
TerminalConfig & TerminalDX12::Core::Config::GetTerminalMut () inline
Definition at line 136 of file Config.h.
GetWarnings()
const std::vector< std::string > & TerminalDX12::Core::Config::GetWarnings () const inline
Definition at line 142 of file Config.h.
IsLoaded()
bool TerminalDX12::Core::Config::IsLoaded () const inline
Definition at line 139 of file Config.h.
Load()
bool TerminalDX12::Core::Config::Load (const std::wstring & path)
Definition at line 154 of file Config.cpp.
Referenced by LoadDefault().
LoadDefault()
bool TerminalDX12::Core::Config::LoadDefault ()
Definition at line 150 of file Config.cpp.
References GetDefaultConfigPath(), and Load().
Save()
bool TerminalDX12::Core::Config::Save (const std::wstring & path) const
Definition at line 386 of file Config.cpp.
References TerminalDX12::Core::Bar, TerminalDX12::Core::Block, TerminalDX12::Core::Underline, and TerminalDX12::Core::WstringToUtf8().
Referenced by CreateDefaultIfMissing().
The documentation for this class was generated from the following files:
include/core/Config.h
src/core/Config.cpp