TerminalDX12: TerminalDX12::Rendering::DX12Renderer Class Reference
TerminalDX12::Rendering::DX12Renderer Class Reference
#include <DX12Renderer.h>
Public Member Functions
DX12Renderer ()
~DX12Renderer ()
bool Initialize (Core::Window *window)
void Shutdown ()
void BeginFrame ()
void EndFrame ()
void Present ()
void Resize (int width, int height)
void RenderText (const std::string &text, float x, float y, float r=1.0f, float g=1.0f, float b=1.0f, float a=1.0f)
void RenderChar (const std::string &ch, float x, float y, float r=1.0f, float g=1.0f, float b=1.0f, float a=1.0f)
void RenderRect (float x, float y, float width, float height, float r, float g, float b, float a=1.0f)
void ClearText ()
ID3D12Device * GetDevice ()
ID3D12GraphicsCommandList * GetCommandList ()
Detailed Description
Definition at line 23 of file DX12Renderer.h.
Constructor & Destructor Documentation
DX12Renderer()
TerminalDX12::Rendering::DX12Renderer::DX12Renderer ()
Definition at line 33 of file DX12Renderer.cpp.
~DX12Renderer()
TerminalDX12::Rendering::DX12Renderer::~DX12Renderer ()
Definition at line 44 of file DX12Renderer.cpp.
References Shutdown().
Member Function Documentation
BeginFrame()
void TerminalDX12::Rendering::DX12Renderer::BeginFrame ()
Definition at line 286 of file DX12Renderer.cpp.
ClearText()
void TerminalDX12::Rendering::DX12Renderer::ClearText ()
Definition at line 704 of file DX12Renderer.cpp.
EndFrame()
void TerminalDX12::Rendering::DX12Renderer::EndFrame ()
Definition at line 338 of file DX12Renderer.cpp.
GetCommandList()
ID3D12GraphicsCommandList * TerminalDX12::Rendering::DX12Renderer::GetCommandList () inline
Definition at line 44 of file DX12Renderer.h.
GetDevice()
ID3D12Device * TerminalDX12::Rendering::DX12Renderer::GetDevice () inline
Definition at line 43 of file DX12Renderer.h.
Initialize()
bool TerminalDX12::Rendering::DX12Renderer::Initialize (Core::Window * window) nodiscard
Definition at line 48 of file DX12Renderer.cpp.
References TerminalDX12::Core::Window::GetHandle(), TerminalDX12::Core::Window::GetHeight(), and TerminalDX12::Core::Window::GetWidth().
Present()
void TerminalDX12::Rendering::DX12Renderer::Present ()
Definition at line 365 of file DX12Renderer.cpp.
RenderChar()
void TerminalDX12::Rendering::DX12Renderer::RenderChar (const std::string & ch, float x, float y, float r = 1.0f, float g = 1.0f, float b = 1.0f, float a = 1.0f)
Definition at line 691 of file DX12Renderer.cpp.
RenderRect()
void TerminalDX12::Rendering::DX12Renderer::RenderRect (float x, float y, float width, float height, float r, float g, float b, float a = 1.0f)
Definition at line 698 of file DX12Renderer.cpp.
RenderText()
void TerminalDX12::Rendering::DX12Renderer::RenderText (const std::string & text, float x, float y, float r = 1.0f, float g = 1.0f, float b = 1.0f, float a = 1.0f)
Definition at line 677 of file DX12Renderer.cpp.
Resize()
void TerminalDX12::Rendering::DX12Renderer::Resize (int width, int height)
Definition at line 374 of file DX12Renderer.cpp.
Shutdown()
void TerminalDX12::Rendering::DX12Renderer::Shutdown ()
Definition at line 89 of file DX12Renderer.cpp.
Referenced by ~DX12Renderer().
The documentation for this class was generated from the following files:
include/rendering/DX12Renderer.h
src/rendering/DX12Renderer.cpp