TerminalDX12: TerminalDX12::UI::Pane Class Reference
TerminalDX12::UI::Pane Class Reference
#include <Pane.h>
Public Member Functions
Pane (Tab *tab)
Pane (SplitDirection direction, std::unique_ptr< Pane > first, std::unique_ptr< Pane > second)
~Pane ()
bool IsLeaf () const
Tab * GetTab ()
const Tab * GetTab () const
SplitDirection GetSplitDirection () const
Pane * GetFirstChild ()
Pane * GetSecondChild ()
const Pane * GetFirstChild () const
const Pane * GetSecondChild () const
float GetSplitRatio () const
void SetSplitRatio (float ratio)
const PaneRect & GetBounds () const
void SetBounds (const PaneRect &bounds)
void CalculateLayout (const PaneRect &availableSpace)
Pane * FindPaneWithTab (Tab *tab)
Pane * FindPaneAt (int x, int y)
void GetAllLeafPanes (std::vector< Pane * > &leaves)
Pane * FindAdjacentPane (Pane *from, SplitDirection direction, bool forward)
Pane * Split (SplitDirection direction, Tab *newTab)
bool CloseChild (Pane *childToClose)
Pane * GetParent ()
void SetParent (Pane *parent)
Detailed Description
Definition at line 26 of file Pane.h.
Constructor & Destructor Documentation
Pane() [1/2]
TerminalDX12::UI::Pane::Pane (Tab * tab) explicit
Definition at line 8 of file Pane.cpp.
Referenced by CloseChild(), FindAdjacentPane(), FindPaneAt(), FindPaneWithTab(), GetFirstChild(), GetFirstChild(), GetParent(), GetSecondChild(), GetSecondChild(), SetParent(), and Split().
Pane() [2/2]
TerminalDX12::UI::Pane::Pane (SplitDirection direction, std::unique_ptr< Pane > first, std::unique_ptr< Pane > second)
Definition at line 14 of file Pane.cpp.
~Pane()
TerminalDX12::UI::Pane::~Pane () default
Member Function Documentation
CalculateLayout()
void TerminalDX12::UI::Pane::CalculateLayout (const PaneRect & availableSpace)
Definition at line 33 of file Pane.cpp.
References TerminalDX12::UI::PaneRect::height, TerminalDX12::UI::Horizontal, IsLeaf(), TerminalDX12::UI::Vertical, TerminalDX12::UI::PaneRect::width, TerminalDX12::UI::PaneRect::x, and TerminalDX12::UI::PaneRect::y.
CloseChild()
bool TerminalDX12::UI::Pane::CloseChild (Pane * childToClose)
Definition at line 209 of file Pane.cpp.
References IsLeaf(), TerminalDX12::UI::None, and Pane().
FindAdjacentPane()
Pane * TerminalDX12::UI::Pane::FindAdjacentPane (Pane * from, SplitDirection direction, bool forward)
Definition at line 152 of file Pane.cpp.
References GetAllLeafPanes(), and Pane().
FindPaneAt()
Pane * TerminalDX12::UI::Pane::FindPaneAt (int x, int y)
Definition at line 114 of file Pane.cpp.
References IsLeaf(), and Pane().
FindPaneWithTab()
Pane * TerminalDX12::UI::Pane::FindPaneWithTab (Tab * tab)
Definition at line 97 of file Pane.cpp.
References IsLeaf(), and Pane().
GetAllLeafPanes()
void TerminalDX12::UI::Pane::GetAllLeafPanes (std::vector< Pane * > & leaves)
Definition at line 138 of file Pane.cpp.
References IsLeaf().
Referenced by FindAdjacentPane().
GetBounds()
const PaneRect & TerminalDX12::UI::Pane::GetBounds () const inline
Definition at line 57 of file Pane.h.
GetFirstChild() [1/2]
Pane * TerminalDX12::UI::Pane::GetFirstChild () inline
Definition at line 47 of file Pane.h.
References Pane().
GetFirstChild() [2/2]
const Pane * TerminalDX12::UI::Pane::GetFirstChild () const inline
Definition at line 49 of file Pane.h.
References Pane().
GetParent()
Pane * TerminalDX12::UI::Pane::GetParent () inline
Definition at line 84 of file Pane.h.
References Pane().
GetSecondChild() [1/2]
Pane * TerminalDX12::UI::Pane::GetSecondChild () inline
Definition at line 48 of file Pane.h.
References Pane().
GetSecondChild() [2/2]
const Pane * TerminalDX12::UI::Pane::GetSecondChild () const inline
Definition at line 50 of file Pane.h.
References Pane().
GetSplitDirection()
SplitDirection TerminalDX12::UI::Pane::GetSplitDirection () const inline
Definition at line 44 of file Pane.h.
GetSplitRatio()
float TerminalDX12::UI::Pane::GetSplitRatio () const inline
Definition at line 53 of file Pane.h.
GetTab() [1/2]
Tab * TerminalDX12::UI::Pane::GetTab () inline
Definition at line 40 of file Pane.h.
GetTab() [2/2]
const Tab * TerminalDX12::UI::Pane::GetTab () const inline
Definition at line 41 of file Pane.h.
IsLeaf()
bool TerminalDX12::UI::Pane::IsLeaf () const inline
Definition at line 37 of file Pane.h.
Referenced by CalculateLayout(), CloseChild(), FindPaneAt(), FindPaneWithTab(), GetAllLeafPanes(), and Split().
SetBounds()
void TerminalDX12::UI::Pane::SetBounds (const PaneRect & bounds) inline
Definition at line 58 of file Pane.h.
SetParent()
void TerminalDX12::UI::Pane::SetParent (Pane * parent) inline
Definition at line 85 of file Pane.h.
References Pane().
SetSplitRatio()
void TerminalDX12::UI::Pane::SetSplitRatio (float ratio)
Definition at line 29 of file Pane.cpp.
Split()
Pane * TerminalDX12::UI::Pane::Split (SplitDirection direction, Tab * newTab)
Definition at line 178 of file Pane.cpp.
References TerminalDX12::UI::Horizontal, IsLeaf(), and Pane().
The documentation for this class was generated from the following files:
include/ui/Pane.h
src/ui/Pane.cpp