TerminalDX12: TerminalDX12::UI::TabManager Class Reference
TerminalDX12::UI::TabManager Class Reference
#include <TabManager.h>
Public Member Functions
TabManager ()
~TabManager ()
Tab * CreateTab (const std::wstring &shell, int cols, int rows, int scrollbackLines=10000)
void CloseTab (int tabId)
void CloseActiveTab ()
void SwitchToTab (int tabId)
void NextTab ()
void PreviousTab ()
Tab * GetActiveTab ()
const Tab * GetActiveTab () const
Tab * GetTab (int tabId)
const std::vector< std::unique_ptr< Tab > > & GetTabs () const
int GetActiveTabIndex () const
size_t GetTabCount () const
bool HasTabs () const
void SetTabChangedCallback (std::function< void()> callback)
void SetActiveTabChangedCallback (std::function< void(Tab *)> callback)
void SetProcessExitCallback (std::function< void(int tabId, int exitCode)> callback)
void SetTabCreatedCallback (std::function< void(Tab *)> callback)
Detailed Description
Definition at line 13 of file TabManager.h.
Constructor & Destructor Documentation
TabManager()
TerminalDX12::UI::TabManager::TabManager () default
~TabManager()
TerminalDX12::UI::TabManager::~TabManager ()
Definition at line 10 of file TabManager.cpp.
Member Function Documentation
CloseActiveTab()
void TerminalDX12::UI::TabManager::CloseActiveTab ()
Definition at line 98 of file TabManager.cpp.
References CloseTab().
CloseTab()
void TerminalDX12::UI::TabManager::CloseTab (int tabId)
Definition at line 56 of file TabManager.cpp.
Referenced by CloseActiveTab().
CreateTab()
Tab * TerminalDX12::UI::TabManager::CreateTab (const std::wstring & shell, int cols, int rows, int scrollbackLines = 10000)
Definition at line 15 of file TabManager.cpp.
GetActiveTab() [1/2]
Tab * TerminalDX12::UI::TabManager::GetActiveTab ()
Definition at line 147 of file TabManager.cpp.
GetActiveTab() [2/2]
const Tab * TerminalDX12::UI::TabManager::GetActiveTab () const
Definition at line 154 of file TabManager.cpp.
GetActiveTabIndex()
int TerminalDX12::UI::TabManager::GetActiveTabIndex () const inline
Definition at line 45 of file TabManager.h.
GetTab()
Tab * TerminalDX12::UI::TabManager::GetTab (int tabId)
Definition at line 161 of file TabManager.cpp.
GetTabCount()
size_t TerminalDX12::UI::TabManager::GetTabCount () const inline
Definition at line 48 of file TabManager.h.
GetTabs()
const std::vector< std::unique_ptr< Tab > > & TerminalDX12::UI::TabManager::GetTabs () const inline
Definition at line 42 of file TabManager.h.
HasTabs()
bool TerminalDX12::UI::TabManager::HasTabs () const inline
Definition at line 51 of file TabManager.h.
NextTab()
void TerminalDX12::UI::TabManager::NextTab ()
Definition at line 126 of file TabManager.cpp.
References SwitchToTab().
PreviousTab()
void TerminalDX12::UI::TabManager::PreviousTab ()
Definition at line 135 of file TabManager.cpp.
References SwitchToTab().
SetActiveTabChangedCallback()
void TerminalDX12::UI::TabManager::SetActiveTabChangedCallback (std::function< void(Tab *)> callback) inline
Definition at line 59 of file TabManager.h.
SetProcessExitCallback()
void TerminalDX12::UI::TabManager::SetProcessExitCallback (std::function< void(int tabId, int exitCode)> callback) inline
Definition at line 64 of file TabManager.h.
SetTabChangedCallback()
void TerminalDX12::UI::TabManager::SetTabChangedCallback (std::function< void()> callback) inline
Definition at line 54 of file TabManager.h.
SetTabCreatedCallback()
void TerminalDX12::UI::TabManager::SetTabCreatedCallback (std::function< void(Tab *)> callback) inline
Definition at line 69 of file TabManager.h.
SwitchToTab()
void TerminalDX12::UI::TabManager::SwitchToTab (int tabId)
Definition at line 104 of file TabManager.cpp.
Referenced by NextTab(), and PreviousTab().
The documentation for this class was generated from the following files:
include/ui/TabManager.h
src/ui/TabManager.cpp